---
- name: Update software, install 
  hosts: all
  remote_user: admin
  tasks:
        - name: Update all software
          yum:
              name: '*'
              state: latest
        - name: Install the nginx from repo rpm
          yum:
              name: 
               - epel-release
               - nginx
               - mysql
               - nodejs
              state: present
        
