        - name: Update all software
          yum:
              name: '*'
              state: latest
        - name: Install the nginx, mysql
          yum:
              name: 
               - epel-release
               - nginx
               - mysql
               - python3
              state: latest  
        - name: Install nodejs
          yum:
              name: nodejs
              state: latest
        - name: Replace ntp default config
          template:
              src: files/nginx.conf
              dest: /etc/nginx/nginx.conf

